version: '3.8'

services:
 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "5001:5000"
  environment:
   - FLASK_ENV=development
  networks:
   - pizzaria-network

 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "8080:80"
  depends_on:
   - backend
  networks:
   - pizzaria-network

networks:
 pizzaria-network:
  driver: bridge
